name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1
  http: ^1.2.2
  objectbox: ^4.0.3
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  objectbox_generator: any
  test: ^1.24.0
